[36m[2021-04-27 16:07:45 DEBUG][39m ###############################################################################
[36m[2021-04-27 16:07:45 DEBUG][39m Running command 'report'
[36m[2021-04-27 16:07:45 DEBUG][39m Using settings file '/.chaostoolkit/settings.yaml'
[33m[2021-04-27 16:07:46 WARNING][39m 
    There is a new version (1.9.0) of the chaostoolkit available.
    You may upgrade by typing:
    
    $ pip install -U chaostoolkit
    
    Please review changes at https://github.com/chaostoolkit/chaostoolkit/blob/master/CHANGELOG.md
    
[36m[2021-04-27 16:07:46 DEBUG][39m Building activity cache...
[36m[2021-04-27 16:07:46 DEBUG][39m Cached 2 activities
[36m[2021-04-27 16:13:44 DEBUG][39m ###############################################################################
[36m[2021-04-27 16:13:44 DEBUG][39m Running command 'report'
[36m[2021-04-27 16:13:44 DEBUG][39m Using settings file '/.chaostoolkit/settings.yaml'
[33m[2021-04-27 16:13:45 WARNING][39m 
    There is a new version (1.9.0) of the chaostoolkit available.
    You may upgrade by typing:
    
    $ pip install -U chaostoolkit
    
    Please review changes at https://github.com/chaostoolkit/chaostoolkit/blob/master/CHANGELOG.md
    
[36m[2021-04-27 16:13:45 DEBUG][39m Building activity cache...
[36m[2021-04-27 16:13:45 DEBUG][39m Cached 2 activities
[36m[2021-04-27 16:25:07 DEBUG][39m ###############################################################################
[36m[2021-04-27 16:25:07 DEBUG][39m Running command 'report'
[36m[2021-04-27 16:25:07 DEBUG][39m Using settings file '/.chaostoolkit/settings.yaml'
[33m[2021-04-27 16:25:09 WARNING][39m 
    There is a new version (1.9.0) of the chaostoolkit available.
    You may upgrade by typing:
    
    $ pip install -U chaostoolkit
    
    Please review changes at https://github.com/chaostoolkit/chaostoolkit/blob/master/CHANGELOG.md
    
[36m[2021-04-27 16:25:09 DEBUG][39m Building activity cache...
[36m[2021-04-27 16:25:09 DEBUG][39m Cached 2 activities
[36m[2021-04-27 18:33:29 DEBUG] [cli:73][39m ###############################################################################
[36m[2021-04-27 18:33:29 DEBUG] [cli:74][39m Running command 'run'
[36m[2021-04-27 18:33:29 DEBUG] [cli:78][39m Using settings file '/home/luisreciomelero/.chaostoolkit/settings.yaml'
[36m[2021-04-27 18:33:30 DEBUG] [__init__:167][39m Loading global control 'chaosiq-cloud'
[36m[2021-04-27 18:33:30 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'loader'
[36m[2021-04-27 18:33:30 DEBUG] [python:166][39m Control 'before_loading_experiment_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:33:30 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'loader'
[36m[2021-04-27 18:33:30 DEBUG] [python:166][39m Control 'after_loading_experiment_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:33:30 DEBUG] [controls:109][39m Using experiment ID 48147c31-72ab-4256-812d-8a1f8d3e28a3 from workspace for experiment at location /home/luisreciomelero/Escritorio/TFM/TFM/chaos/experiments-pre-changes/networking-experiments/delay-experiments/delay-mg.yaml
[36m[2021-04-27 18:33:30 DEBUG] [caching:25][39m Building activity cache...
[36m[2021-04-27 18:33:30 DEBUG] [caching:35][39m Cached 2 activities
[32m[2021-04-27 18:33:30 INFO] [experiment:47][39m Validating the experiment's syntax
[36m[2021-04-27 18:33:30 DEBUG] [configuration:54][39m Loading configuration...
[36m[2021-04-27 18:33:30 DEBUG] [secret:75][39m Loading secrets...
[36m[2021-04-27 18:33:30 DEBUG] [secret:92][39m Secrets loaded
[32m[2021-04-27 18:33:30 INFO] [experiment:96][39m Experiment looks valid
[36m[2021-04-27 18:33:30 DEBUG] [caching:42][39m Clearing activities cache
[36m[2021-04-27 18:33:30 DEBUG] [caching:25][39m Building activity cache...
[36m[2021-04-27 18:33:30 DEBUG] [caching:35][39m Cached 2 activities
[36m[2021-04-27 18:33:30 DEBUG] [configuration:54][39m Loading configuration...
[36m[2021-04-27 18:33:30 DEBUG] [secret:75][39m Loading secrets...
[36m[2021-04-27 18:33:30 DEBUG] [secret:92][39m Secrets loaded
[32m[2021-04-27 18:33:30 INFO] [run:323][39m Running experiment: What happens if we abort and delay responses
[36m[2021-04-27 18:33:30 DEBUG] [__init__:136][39m Initializing global control 'chaosiq-cloud'
[36m[2021-04-27 18:33:30 DEBUG] [python:166][39m Control 'configure_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:33:33 INFO] [execution:64][39m Execution available at http://console.chaosiq.io/tfm/luisreciomelero/executions/a6903df0-7d0e-40c8-bbbc-2485ad153e17
[36m[2021-04-27 18:33:33 DEBUG] [workspace:108][39m Saving workspace at /home/luisreciomelero/Escritorio/TFM/TFM/chaos/experiments-pre-changes/networking-experiments/delay-experiments/.chaosiq
[36m[2021-04-27 18:33:33 DEBUG] [__init__:39][39m Initializing controls
[32m[2021-04-27 18:33:33 INFO] [run:342][39m Steady-state strategy: default
[32m[2021-04-27 18:33:33 INFO] [run:345][39m Rollbacks strategy: always
[36m[2021-04-27 18:33:33 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'experiment'
[36m[2021-04-27 18:33:33 DEBUG] [python:166][39m Control 'before_experiment_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:33:34 DEBUG] [run:466][39m Running steady-state hypothesis before the method
[32m[2021-04-27 18:33:34 INFO] [hypothesis:183][39m Steady state hypothesis: The app is healthy
[36m[2021-04-27 18:33:34 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'hypothesis'
[36m[2021-04-27 18:33:34 DEBUG] [python:166][39m Control 'before_hypothesis_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:33:36 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:33:36 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:33:38 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-27 18:33:38 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '10', 'date': 'Tue, 27 Apr 2021 16:33:37 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-27 18:33:38 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:33:38 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:33:39 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-27 18:33:39 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:33:39 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:33:41 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-27 18:33:41 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '6', 'date': 'Tue, 27 Apr 2021 16:33:41 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-27 18:33:41 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:33:41 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:33:42 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-27 18:33:42 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:33:42 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:33:44 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-27 18:33:44 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '30', 'date': 'Tue, 27 Apr 2021 16:33:44 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-27 18:33:44 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:33:44 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:33:46 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-27 18:33:46 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:33:46 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:33:47 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-27 18:33:47 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '6', 'date': 'Tue, 27 Apr 2021 16:33:47 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-27 18:33:47 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:33:47 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:33:49 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-27 18:33:49 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:33:49 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:33:50 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-27 18:33:50 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '10', 'date': 'Tue, 27 Apr 2021 16:33:50 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-27 18:33:50 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:33:50 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:33:52 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[32m[2021-04-27 18:33:52 INFO] [hypothesis:221][39m Steady state hypothesis is met!
[36m[2021-04-27 18:33:52 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'hypothesis'
[36m[2021-04-27 18:33:52 DEBUG] [python:166][39m Control 'after_hypothesis_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:33:54 INFO] [run:553][39m Playing your experiment's method now...
[36m[2021-04-27 18:33:54 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'method'
[36m[2021-04-27 18:33:54 DEBUG] [python:166][39m Control 'before_method_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:33:55 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:33:55 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:33:57 INFO] [activity:161][39m Action: delay
[36m[2021-04-27 18:33:57 DEBUG] [python:34][39m Activity 'delay' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosistio/fault/actions.py'
[36m[2021-04-27 18:33:57 DEBUG] [__init__:67][39m Using Kubernetes context: default
[36m[2021-04-27 18:33:57 DEBUG] [__init__:67][39m Using Kubernetes context: default
[36m[2021-04-27 18:33:57 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'body': {'apiVersion': 'networking.istio.io/v1alpha3', 'kind': 'VirtualService', 'metadata': {'annotations': {'kubectl.kubernetes.io/last-applied-configuration': '{"apiVersion":"networking.istio.io/v1alpha3","kind":"VirtualService","metadata":{"annotations":{},"name":"mg-v1-vs","namespace":"default"},"spec":{"hosts":["mg-v1"],"http":[{"route":[{"destination":{"host":"mg-v1","port":{"number":8081},"subset":"primary"}}]}]}}\n'}, 'creationTimestamp': '2021-04-26T19:12:53Z', 'generation': 2, 'managedFields': [{'apiVersion': 'networking.istio.io/v1alpha3', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:annotations': {'.': {}, 'f:kubectl.kubernetes.io/last-applied-configuration': {}}}, 'f:spec': {'.': {}, 'f:hosts': {}, 'f:http': {}}}, 'manager': 'kubectl-client-side-apply', 'operation': 'Update', 'time': '2021-04-26T19:12:53Z'}], 'name': 'mg-v1-vs', 'namespace': 'default', 'resourceVersion': '3504', 'uid': '14949f29-652e-4db8-8951-371976c9fe8f'}, 'spec': {'hosts': ['mg-v1'], 'http': [{'route': [{'destination': {'host': 'mg-v1', 'port': {'number': 8081}, 'subset': 'primary'}}]}]}}, 'headers': {'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': 'ca338ed9-6f9e-4cbe-97a8-df98999be000', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'b23d468f-1284-456c-b90c-415700e009a5', 'Date': 'Tue, 27 Apr 2021 16:33:57 GMT', 'Content-Length': '1081'}}'
[32m[2021-04-27 18:33:57 INFO] [activity:198][39m Pausing after activity for 5s...
[36m[2021-04-27 18:34:02 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:34:02 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:34:04 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'method'
[36m[2021-04-27 18:34:04 DEBUG] [python:166][39m Control 'after_method_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:34:06 DEBUG] [run:496][39m Running steady-state hypothesis after the method
[32m[2021-04-27 18:34:06 INFO] [hypothesis:183][39m Steady state hypothesis: The app is healthy
[36m[2021-04-27 18:34:06 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'hypothesis'
[36m[2021-04-27 18:34:06 DEBUG] [python:166][39m Control 'before_hypothesis_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:34:07 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:34:07 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:34:09 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-27 18:34:09 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '10', 'date': 'Tue, 27 Apr 2021 16:34:09 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-27 18:34:09 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:34:09 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:34:10 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-27 18:34:10 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:34:10 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:34:12 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-27 18:34:12 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '8', 'date': 'Tue, 27 Apr 2021 16:34:12 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-27 18:34:12 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:34:12 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:34:13 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-27 18:34:13 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:34:13 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:34:15 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-27 18:34:15 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '7', 'date': 'Tue, 27 Apr 2021 16:34:15 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-27 18:34:15 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:34:15 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:34:17 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-27 18:34:17 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:34:17 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:34:18 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-27 18:34:18 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '20', 'date': 'Tue, 27 Apr 2021 16:34:18 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-27 18:34:18 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:34:18 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:34:20 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-27 18:34:20 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:34:20 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:34:21 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-27 18:34:21 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '8', 'date': 'Tue, 27 Apr 2021 16:34:21 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-27 18:34:21 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:34:21 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:34:23 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[32m[2021-04-27 18:34:23 INFO] [hypothesis:221][39m Steady state hypothesis is met!
[36m[2021-04-27 18:34:23 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'hypothesis'
[36m[2021-04-27 18:34:23 DEBUG] [python:166][39m Control 'after_hypothesis_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[33m[2021-04-27 18:34:25 WARNING] [run:580][39m Rollbacks were explicitly requested to be played
[32m[2021-04-27 18:34:25 INFO] [run:809][39m Let's rollback...
[36m[2021-04-27 18:34:25 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'rollback'
[36m[2021-04-27 18:34:25 DEBUG] [python:166][39m Control 'before_rollback_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:34:26 INFO] [rollback:28][39m Rollback: remove-delay
[36m[2021-04-27 18:34:26 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:34:26 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:34:28 INFO] [activity:161][39m Action: remove-delay
[36m[2021-04-27 18:34:28 DEBUG] [python:34][39m Activity 'remove-delay' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosistio/fault/actions.py'
[36m[2021-04-27 18:34:28 DEBUG] [__init__:67][39m Using Kubernetes context: default
[36m[2021-04-27 18:34:28 DEBUG] [__init__:67][39m Using Kubernetes context: default
[36m[2021-04-27 18:34:28 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'body': {'apiVersion': 'networking.istio.io/v1alpha3', 'kind': 'VirtualService', 'metadata': {'annotations': {'kubectl.kubernetes.io/last-applied-configuration': '{"apiVersion":"networking.istio.io/v1alpha3","kind":"VirtualService","metadata":{"annotations":{},"name":"mg-v1-vs","namespace":"default"},"spec":{"hosts":["mg-v1"],"http":[{"route":[{"destination":{"host":"mg-v1","port":{"number":8081},"subset":"primary"}}]}]}}\n'}, 'creationTimestamp': '2021-04-26T19:12:53Z', 'generation': 2, 'managedFields': [{'apiVersion': 'networking.istio.io/v1alpha3', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:annotations': {'.': {}, 'f:kubectl.kubernetes.io/last-applied-configuration': {}}}, 'f:spec': {'.': {}, 'f:hosts': {}, 'f:http': {}}}, 'manager': 'kubectl-client-side-apply', 'operation': 'Update', 'time': '2021-04-26T19:12:53Z'}], 'name': 'mg-v1-vs', 'namespace': 'default', 'resourceVersion': '3504', 'uid': '14949f29-652e-4db8-8951-371976c9fe8f'}, 'spec': {'hosts': ['mg-v1'], 'http': [{'route': [{'destination': {'host': 'mg-v1', 'port': {'number': 8081}, 'subset': 'primary'}}]}]}}, 'headers': {'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': 'ca338ed9-6f9e-4cbe-97a8-df98999be000', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'b23d468f-1284-456c-b90c-415700e009a5', 'Date': 'Tue, 27 Apr 2021 16:34:28 GMT', 'Content-Length': '1081'}}'
[36m[2021-04-27 18:34:28 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:34:28 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:34:30 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'rollback'
[36m[2021-04-27 18:34:30 DEBUG] [python:166][39m Control 'after_rollback_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:34:31 INFO] [run:421][39m Experiment ended with status: completed
[36m[2021-04-27 18:34:31 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'experiment'
[36m[2021-04-27 18:34:31 DEBUG] [python:166][39m Control 'after_experiment_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:34:34 DEBUG] [__init__:72][39m Cleaning up controls
[36m[2021-04-27 18:34:34 DEBUG] [__init__:188][39m Cleaning up global control 'chaosiq-cloud'
[36m[2021-04-27 18:34:34 DEBUG] [python:159][39m Control module '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py' does not declare 'cleanup_control'
[36m[2021-04-27 18:34:34 DEBUG] [caching:42][39m Clearing activities cache
[36m[2021-04-27 16:35:24 DEBUG][39m ###############################################################################
[36m[2021-04-27 16:35:24 DEBUG][39m Running command 'report'
[36m[2021-04-27 16:35:24 DEBUG][39m Using settings file '/.chaostoolkit/settings.yaml'
[33m[2021-04-27 16:35:26 WARNING][39m 
    There is a new version (1.9.0) of the chaostoolkit available.
    You may upgrade by typing:
    
    $ pip install -U chaostoolkit
    
    Please review changes at https://github.com/chaostoolkit/chaostoolkit/blob/master/CHANGELOG.md
    
[36m[2021-04-27 16:35:26 DEBUG][39m Building activity cache...
[36m[2021-04-27 16:35:26 DEBUG][39m Cached 2 activities
[36m[2021-04-27 18:39:22 DEBUG] [cli:73][39m ###############################################################################
[36m[2021-04-27 18:39:22 DEBUG] [cli:74][39m Running command 'run'
[36m[2021-04-27 18:39:22 DEBUG] [cli:78][39m Using settings file '/home/luisreciomelero/.chaostoolkit/settings.yaml'
[36m[2021-04-27 18:39:23 DEBUG] [__init__:167][39m Loading global control 'chaosiq-cloud'
[36m[2021-04-27 18:39:23 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'loader'
[36m[2021-04-27 18:39:23 DEBUG] [python:166][39m Control 'before_loading_experiment_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:39:23 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'loader'
[36m[2021-04-27 18:39:23 DEBUG] [python:166][39m Control 'after_loading_experiment_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:39:23 DEBUG] [controls:109][39m Using experiment ID 48147c31-72ab-4256-812d-8a1f8d3e28a3 from workspace for experiment at location /home/luisreciomelero/Escritorio/TFM/TFM/chaos/experiments-pre-changes/networking-experiments/delay-experiments/delay-mg.yaml
[36m[2021-04-27 18:39:23 DEBUG] [caching:25][39m Building activity cache...
[36m[2021-04-27 18:39:23 DEBUG] [caching:35][39m Cached 2 activities
[32m[2021-04-27 18:39:23 INFO] [experiment:47][39m Validating the experiment's syntax
[36m[2021-04-27 18:39:23 DEBUG] [configuration:54][39m Loading configuration...
[36m[2021-04-27 18:39:23 DEBUG] [secret:75][39m Loading secrets...
[36m[2021-04-27 18:39:23 DEBUG] [secret:92][39m Secrets loaded
[32m[2021-04-27 18:39:25 INFO] [experiment:96][39m Experiment looks valid
[36m[2021-04-27 18:39:25 DEBUG] [caching:42][39m Clearing activities cache
[36m[2021-04-27 18:39:25 DEBUG] [caching:25][39m Building activity cache...
[36m[2021-04-27 18:39:25 DEBUG] [caching:35][39m Cached 2 activities
[36m[2021-04-27 18:39:25 DEBUG] [configuration:54][39m Loading configuration...
[36m[2021-04-27 18:39:25 DEBUG] [secret:75][39m Loading secrets...
[36m[2021-04-27 18:39:25 DEBUG] [secret:92][39m Secrets loaded
[32m[2021-04-27 18:39:25 INFO] [run:323][39m Running experiment: What happens if we abort and delay responses
[36m[2021-04-27 18:39:25 DEBUG] [__init__:136][39m Initializing global control 'chaosiq-cloud'
[36m[2021-04-27 18:39:25 DEBUG] [python:166][39m Control 'configure_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:39:28 INFO] [execution:64][39m Execution available at http://console.chaosiq.io/tfm/luisreciomelero/executions/92e984c8-bec2-4857-9223-89fd9bc47bfe
[36m[2021-04-27 18:39:28 DEBUG] [workspace:108][39m Saving workspace at /home/luisreciomelero/Escritorio/TFM/TFM/chaos/experiments-pre-changes/networking-experiments/delay-experiments/.chaosiq
[36m[2021-04-27 18:39:28 DEBUG] [__init__:39][39m Initializing controls
[32m[2021-04-27 18:39:28 INFO] [run:342][39m Steady-state strategy: default
[32m[2021-04-27 18:39:28 INFO] [run:345][39m Rollbacks strategy: always
[36m[2021-04-27 18:39:28 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'experiment'
[36m[2021-04-27 18:39:28 DEBUG] [python:166][39m Control 'before_experiment_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:39:29 DEBUG] [run:466][39m Running steady-state hypothesis before the method
[32m[2021-04-27 18:39:29 INFO] [hypothesis:183][39m Steady state hypothesis: The app is healthy
[36m[2021-04-27 18:39:29 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'hypothesis'
[36m[2021-04-27 18:39:29 DEBUG] [python:166][39m Control 'before_hypothesis_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:39:31 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:39:31 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:39:33 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-27 18:39:33 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '6', 'date': 'Tue, 27 Apr 2021 16:39:32 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-27 18:39:33 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:39:33 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:39:34 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-27 18:39:34 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:39:34 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:39:36 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-27 18:39:36 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '11', 'date': 'Tue, 27 Apr 2021 16:39:35 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-27 18:39:36 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:39:36 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:39:37 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-27 18:39:37 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:39:37 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:39:39 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-27 18:39:39 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '21', 'date': 'Tue, 27 Apr 2021 16:39:39 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-27 18:39:39 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:39:39 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:39:41 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-27 18:39:41 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:39:41 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:39:42 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-27 18:39:42 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '6', 'date': 'Tue, 27 Apr 2021 16:39:42 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-27 18:39:42 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:39:42 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:39:44 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-27 18:39:44 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:39:44 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:39:45 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-27 18:39:45 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '25', 'date': 'Tue, 27 Apr 2021 16:39:45 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-27 18:39:45 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:39:45 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:39:47 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[32m[2021-04-27 18:39:47 INFO] [hypothesis:221][39m Steady state hypothesis is met!
[36m[2021-04-27 18:39:47 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'hypothesis'
[36m[2021-04-27 18:39:47 DEBUG] [python:166][39m Control 'after_hypothesis_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:39:49 INFO] [run:553][39m Playing your experiment's method now...
[36m[2021-04-27 18:39:49 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'method'
[36m[2021-04-27 18:39:49 DEBUG] [python:166][39m Control 'before_method_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:39:50 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:39:50 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:39:52 INFO] [activity:161][39m Action: delay
[36m[2021-04-27 18:39:52 DEBUG] [python:34][39m Activity 'delay' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosistio/fault/actions.py'
[36m[2021-04-27 18:39:52 DEBUG] [__init__:67][39m Using Kubernetes context: default
[36m[2021-04-27 18:39:52 DEBUG] [__init__:67][39m Using Kubernetes context: default
[36m[2021-04-27 18:39:52 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'body': {'apiVersion': 'networking.istio.io/v1alpha3', 'kind': 'VirtualService', 'metadata': {'annotations': {'kubectl.kubernetes.io/last-applied-configuration': '{"apiVersion":"networking.istio.io/v1alpha3","kind":"VirtualService","metadata":{"annotations":{},"name":"mg-v1-vs","namespace":"default"},"spec":{"hosts":["mg-v1"],"http":[{"route":[{"destination":{"host":"mg-v1","port":{"number":8081},"subset":"primary"}}]}]}}\n'}, 'creationTimestamp': '2021-04-26T19:12:53Z', 'generation': 2, 'managedFields': [{'apiVersion': 'networking.istio.io/v1alpha3', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:annotations': {'.': {}, 'f:kubectl.kubernetes.io/last-applied-configuration': {}}}, 'f:spec': {'.': {}, 'f:hosts': {}, 'f:http': {}}}, 'manager': 'kubectl-client-side-apply', 'operation': 'Update', 'time': '2021-04-26T19:12:53Z'}], 'name': 'mg-v1-vs', 'namespace': 'default', 'resourceVersion': '3504', 'uid': '14949f29-652e-4db8-8951-371976c9fe8f'}, 'spec': {'hosts': ['mg-v1'], 'http': [{'route': [{'destination': {'host': 'mg-v1', 'port': {'number': 8081}, 'subset': 'primary'}}]}]}}, 'headers': {'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': 'ca338ed9-6f9e-4cbe-97a8-df98999be000', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'b23d468f-1284-456c-b90c-415700e009a5', 'Date': 'Tue, 27 Apr 2021 16:39:52 GMT', 'Content-Length': '1081'}}'
[32m[2021-04-27 18:39:52 INFO] [activity:198][39m Pausing after activity for 5s...
[36m[2021-04-27 18:39:57 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:39:57 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:39:59 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'method'
[36m[2021-04-27 18:39:59 DEBUG] [python:166][39m Control 'after_method_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:40:00 DEBUG] [run:496][39m Running steady-state hypothesis after the method
[32m[2021-04-27 18:40:00 INFO] [hypothesis:183][39m Steady state hypothesis: The app is healthy
[36m[2021-04-27 18:40:00 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'hypothesis'
[36m[2021-04-27 18:40:00 DEBUG] [python:166][39m Control 'before_hypothesis_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:40:02 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:40:02 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:40:04 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-27 18:40:04 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '6', 'date': 'Tue, 27 Apr 2021 16:40:03 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-27 18:40:04 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:40:04 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:40:05 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-27 18:40:05 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:40:05 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:40:07 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-27 18:40:07 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '5', 'date': 'Tue, 27 Apr 2021 16:40:06 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-27 18:40:07 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:40:07 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:40:08 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-27 18:40:08 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:40:08 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:40:10 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-27 18:40:10 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '6', 'date': 'Tue, 27 Apr 2021 16:40:10 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-27 18:40:10 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:40:10 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:40:12 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-27 18:40:12 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:40:12 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:40:13 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-27 18:40:14 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '21', 'date': 'Tue, 27 Apr 2021 16:40:13 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-27 18:40:14 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:40:14 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:40:15 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-27 18:40:15 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:40:15 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:40:17 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-27 18:40:17 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '11', 'date': 'Tue, 27 Apr 2021 16:40:16 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-27 18:40:17 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:40:17 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:40:18 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[32m[2021-04-27 18:40:18 INFO] [hypothesis:221][39m Steady state hypothesis is met!
[36m[2021-04-27 18:40:18 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'hypothesis'
[36m[2021-04-27 18:40:18 DEBUG] [python:166][39m Control 'after_hypothesis_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[33m[2021-04-27 18:40:20 WARNING] [run:580][39m Rollbacks were explicitly requested to be played
[32m[2021-04-27 18:40:20 INFO] [run:809][39m Let's rollback...
[36m[2021-04-27 18:40:20 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'rollback'
[36m[2021-04-27 18:40:20 DEBUG] [python:166][39m Control 'before_rollback_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:40:22 INFO] [rollback:28][39m Rollback: remove-delay
[36m[2021-04-27 18:40:22 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:40:22 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:40:23 INFO] [activity:161][39m Action: remove-delay
[36m[2021-04-27 18:40:23 DEBUG] [python:34][39m Activity 'remove-delay' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosistio/fault/actions.py'
[36m[2021-04-27 18:40:23 DEBUG] [__init__:67][39m Using Kubernetes context: default
[36m[2021-04-27 18:40:23 DEBUG] [__init__:67][39m Using Kubernetes context: default
[36m[2021-04-27 18:40:23 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'body': {'apiVersion': 'networking.istio.io/v1alpha3', 'kind': 'VirtualService', 'metadata': {'annotations': {'kubectl.kubernetes.io/last-applied-configuration': '{"apiVersion":"networking.istio.io/v1alpha3","kind":"VirtualService","metadata":{"annotations":{},"name":"mg-v1-vs","namespace":"default"},"spec":{"hosts":["mg-v1"],"http":[{"route":[{"destination":{"host":"mg-v1","port":{"number":8081},"subset":"primary"}}]}]}}\n'}, 'creationTimestamp': '2021-04-26T19:12:53Z', 'generation': 2, 'managedFields': [{'apiVersion': 'networking.istio.io/v1alpha3', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:annotations': {'.': {}, 'f:kubectl.kubernetes.io/last-applied-configuration': {}}}, 'f:spec': {'.': {}, 'f:hosts': {}, 'f:http': {}}}, 'manager': 'kubectl-client-side-apply', 'operation': 'Update', 'time': '2021-04-26T19:12:53Z'}], 'name': 'mg-v1-vs', 'namespace': 'default', 'resourceVersion': '3504', 'uid': '14949f29-652e-4db8-8951-371976c9fe8f'}, 'spec': {'hosts': ['mg-v1'], 'http': [{'route': [{'destination': {'host': 'mg-v1', 'port': {'number': 8081}, 'subset': 'primary'}}]}]}}, 'headers': {'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': 'ca338ed9-6f9e-4cbe-97a8-df98999be000', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'b23d468f-1284-456c-b90c-415700e009a5', 'Date': 'Tue, 27 Apr 2021 16:40:23 GMT', 'Content-Length': '1081'}}'
[36m[2021-04-27 18:40:23 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:40:23 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:40:25 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'rollback'
[36m[2021-04-27 18:40:25 DEBUG] [python:166][39m Control 'after_rollback_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:40:27 INFO] [run:421][39m Experiment ended with status: completed
[36m[2021-04-27 18:40:27 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'experiment'
[36m[2021-04-27 18:40:27 DEBUG] [python:166][39m Control 'after_experiment_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:40:29 DEBUG] [__init__:72][39m Cleaning up controls
[36m[2021-04-27 18:40:29 DEBUG] [__init__:188][39m Cleaning up global control 'chaosiq-cloud'
[36m[2021-04-27 18:40:29 DEBUG] [python:159][39m Control module '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py' does not declare 'cleanup_control'
[36m[2021-04-27 18:40:29 DEBUG] [caching:42][39m Clearing activities cache
[36m[2021-04-27 16:41:23 DEBUG][39m ###############################################################################
[36m[2021-04-27 16:41:23 DEBUG][39m Running command 'report'
[36m[2021-04-27 16:41:23 DEBUG][39m Using settings file '/.chaostoolkit/settings.yaml'
[33m[2021-04-27 16:41:24 WARNING][39m 
    There is a new version (1.9.0) of the chaostoolkit available.
    You may upgrade by typing:
    
    $ pip install -U chaostoolkit
    
    Please review changes at https://github.com/chaostoolkit/chaostoolkit/blob/master/CHANGELOG.md
    
[36m[2021-04-27 16:41:24 DEBUG][39m Building activity cache...
[36m[2021-04-27 16:41:24 DEBUG][39m Cached 2 activities
[36m[2021-04-27 18:45:15 DEBUG] [cli:73][39m ###############################################################################
[36m[2021-04-27 18:45:15 DEBUG] [cli:74][39m Running command 'run'
[36m[2021-04-27 18:45:15 DEBUG] [cli:78][39m Using settings file '/home/luisreciomelero/.chaostoolkit/settings.yaml'
[36m[2021-04-27 18:45:16 DEBUG] [__init__:167][39m Loading global control 'chaosiq-cloud'
[36m[2021-04-27 18:45:16 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'loader'
[36m[2021-04-27 18:45:16 DEBUG] [python:166][39m Control 'before_loading_experiment_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:45:16 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'loader'
[36m[2021-04-27 18:45:16 DEBUG] [python:166][39m Control 'after_loading_experiment_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:45:16 DEBUG] [controls:109][39m Using experiment ID 48147c31-72ab-4256-812d-8a1f8d3e28a3 from workspace for experiment at location /home/luisreciomelero/Escritorio/TFM/TFM/chaos/experiments-pre-changes/networking-experiments/delay-experiments/delay-mg.yaml
[36m[2021-04-27 18:45:16 DEBUG] [caching:25][39m Building activity cache...
[36m[2021-04-27 18:45:16 DEBUG] [caching:35][39m Cached 2 activities
[32m[2021-04-27 18:45:16 INFO] [experiment:47][39m Validating the experiment's syntax
[36m[2021-04-27 18:45:16 DEBUG] [configuration:54][39m Loading configuration...
[36m[2021-04-27 18:45:16 DEBUG] [secret:75][39m Loading secrets...
[36m[2021-04-27 18:45:16 DEBUG] [secret:92][39m Secrets loaded
[32m[2021-04-27 18:45:16 INFO] [experiment:96][39m Experiment looks valid
[36m[2021-04-27 18:45:16 DEBUG] [caching:42][39m Clearing activities cache
[36m[2021-04-27 18:45:16 DEBUG] [caching:25][39m Building activity cache...
[36m[2021-04-27 18:45:16 DEBUG] [caching:35][39m Cached 2 activities
[36m[2021-04-27 18:45:16 DEBUG] [configuration:54][39m Loading configuration...
[36m[2021-04-27 18:45:16 DEBUG] [secret:75][39m Loading secrets...
[36m[2021-04-27 18:45:16 DEBUG] [secret:92][39m Secrets loaded
[32m[2021-04-27 18:45:16 INFO] [run:323][39m Running experiment: What happens if we abort and delay responses
[36m[2021-04-27 18:45:16 DEBUG] [__init__:136][39m Initializing global control 'chaosiq-cloud'
[36m[2021-04-27 18:45:16 DEBUG] [python:166][39m Control 'configure_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:45:18 INFO] [execution:64][39m Execution available at http://console.chaosiq.io/tfm/luisreciomelero/executions/1c7ac105-7d41-4ee4-8fc6-83c3da217864
[36m[2021-04-27 18:45:18 DEBUG] [workspace:108][39m Saving workspace at /home/luisreciomelero/Escritorio/TFM/TFM/chaos/experiments-pre-changes/networking-experiments/delay-experiments/.chaosiq
[36m[2021-04-27 18:45:18 DEBUG] [__init__:39][39m Initializing controls
[32m[2021-04-27 18:45:18 INFO] [run:342][39m Steady-state strategy: default
[32m[2021-04-27 18:45:18 INFO] [run:345][39m Rollbacks strategy: always
[36m[2021-04-27 18:45:18 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'experiment'
[36m[2021-04-27 18:45:18 DEBUG] [python:166][39m Control 'before_experiment_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:45:20 DEBUG] [run:466][39m Running steady-state hypothesis before the method
[32m[2021-04-27 18:45:20 INFO] [hypothesis:183][39m Steady state hypothesis: The app is healthy
[36m[2021-04-27 18:45:20 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'hypothesis'
[36m[2021-04-27 18:45:20 DEBUG] [python:166][39m Control 'before_hypothesis_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:45:22 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:45:22 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:45:24 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-27 18:45:24 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '20', 'date': 'Tue, 27 Apr 2021 16:45:24 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-27 18:45:24 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:45:24 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:45:25 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-27 18:45:25 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:45:25 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:45:27 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-27 18:45:27 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '7', 'date': 'Tue, 27 Apr 2021 16:45:26 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-27 18:45:27 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:45:27 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:45:28 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-27 18:45:28 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:45:28 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:45:30 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-27 18:45:30 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '9', 'date': 'Tue, 27 Apr 2021 16:45:30 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-27 18:45:30 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:45:30 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:45:32 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-27 18:45:32 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:45:32 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:45:33 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-27 18:45:33 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '18', 'date': 'Tue, 27 Apr 2021 16:45:33 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-27 18:45:33 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:45:33 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:45:35 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-27 18:45:35 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:45:35 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:45:36 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-27 18:45:36 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '20', 'date': 'Tue, 27 Apr 2021 16:45:36 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-27 18:45:36 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:45:36 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:45:38 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[32m[2021-04-27 18:45:38 INFO] [hypothesis:221][39m Steady state hypothesis is met!
[36m[2021-04-27 18:45:38 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'hypothesis'
[36m[2021-04-27 18:45:38 DEBUG] [python:166][39m Control 'after_hypothesis_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:45:40 INFO] [run:553][39m Playing your experiment's method now...
[36m[2021-04-27 18:45:40 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'method'
[36m[2021-04-27 18:45:40 DEBUG] [python:166][39m Control 'before_method_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:45:41 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:45:41 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:45:43 INFO] [activity:161][39m Action: delay
[36m[2021-04-27 18:45:43 DEBUG] [python:34][39m Activity 'delay' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosistio/fault/actions.py'
[36m[2021-04-27 18:45:43 DEBUG] [__init__:67][39m Using Kubernetes context: default
[36m[2021-04-27 18:45:44 DEBUG] [__init__:67][39m Using Kubernetes context: default
[36m[2021-04-27 18:45:44 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'body': {'apiVersion': 'networking.istio.io/v1alpha3', 'kind': 'VirtualService', 'metadata': {'annotations': {'kubectl.kubernetes.io/last-applied-configuration': '{"apiVersion":"networking.istio.io/v1alpha3","kind":"VirtualService","metadata":{"annotations":{},"name":"mg-v1-vs","namespace":"default"},"spec":{"hosts":["mg-v1"],"http":[{"route":[{"destination":{"host":"mg-v1","port":{"number":8081},"subset":"primary"}}]}]}}\n'}, 'creationTimestamp': '2021-04-26T19:12:53Z', 'generation': 2, 'managedFields': [{'apiVersion': 'networking.istio.io/v1alpha3', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:annotations': {'.': {}, 'f:kubectl.kubernetes.io/last-applied-configuration': {}}}, 'f:spec': {'.': {}, 'f:hosts': {}, 'f:http': {}}}, 'manager': 'kubectl-client-side-apply', 'operation': 'Update', 'time': '2021-04-26T19:12:53Z'}], 'name': 'mg-v1-vs', 'namespace': 'default', 'resourceVersion': '3504', 'uid': '14949f29-652e-4db8-8951-371976c9fe8f'}, 'spec': {'hosts': ['mg-v1'], 'http': [{'route': [{'destination': {'host': 'mg-v1', 'port': {'number': 8081}, 'subset': 'primary'}}]}]}}, 'headers': {'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': 'ca338ed9-6f9e-4cbe-97a8-df98999be000', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'b23d468f-1284-456c-b90c-415700e009a5', 'Date': 'Tue, 27 Apr 2021 16:45:44 GMT', 'Content-Length': '1081'}}'
[32m[2021-04-27 18:45:44 INFO] [activity:198][39m Pausing after activity for 5s...
[36m[2021-04-27 18:45:49 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:45:49 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:45:50 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'method'
[36m[2021-04-27 18:45:50 DEBUG] [python:166][39m Control 'after_method_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:45:52 DEBUG] [run:496][39m Running steady-state hypothesis after the method
[32m[2021-04-27 18:45:52 INFO] [hypothesis:183][39m Steady state hypothesis: The app is healthy
[36m[2021-04-27 18:45:52 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'hypothesis'
[36m[2021-04-27 18:45:52 DEBUG] [python:166][39m Control 'before_hypothesis_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:45:54 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:45:54 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:45:55 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-27 18:45:55 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '5', 'date': 'Tue, 27 Apr 2021 16:45:55 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-27 18:45:55 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:45:55 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:45:57 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-27 18:45:57 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:45:57 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:45:58 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-27 18:45:58 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '5', 'date': 'Tue, 27 Apr 2021 16:45:58 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-27 18:45:58 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:45:58 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:46:00 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-27 18:46:00 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:46:00 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:46:01 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-27 18:46:01 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '5', 'date': 'Tue, 27 Apr 2021 16:46:01 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-27 18:46:01 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:46:01 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:46:03 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-27 18:46:03 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:46:03 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:46:05 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-27 18:46:05 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '7', 'date': 'Tue, 27 Apr 2021 16:46:04 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-27 18:46:05 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:46:05 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:46:06 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-27 18:46:06 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:46:06 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:46:08 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-27 18:46:08 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '27', 'date': 'Tue, 27 Apr 2021 16:46:08 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-27 18:46:08 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:46:08 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:46:09 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[32m[2021-04-27 18:46:09 INFO] [hypothesis:221][39m Steady state hypothesis is met!
[36m[2021-04-27 18:46:09 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'hypothesis'
[36m[2021-04-27 18:46:09 DEBUG] [python:166][39m Control 'after_hypothesis_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[33m[2021-04-27 18:46:11 WARNING] [run:580][39m Rollbacks were explicitly requested to be played
[32m[2021-04-27 18:46:11 INFO] [run:809][39m Let's rollback...
[36m[2021-04-27 18:46:11 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'rollback'
[36m[2021-04-27 18:46:11 DEBUG] [python:166][39m Control 'before_rollback_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:46:13 INFO] [rollback:28][39m Rollback: remove-delay
[36m[2021-04-27 18:46:13 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:46:13 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:46:14 INFO] [activity:161][39m Action: remove-delay
[36m[2021-04-27 18:46:14 DEBUG] [python:34][39m Activity 'remove-delay' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosistio/fault/actions.py'
[36m[2021-04-27 18:46:14 DEBUG] [__init__:67][39m Using Kubernetes context: default
[36m[2021-04-27 18:46:15 DEBUG] [__init__:67][39m Using Kubernetes context: default
[36m[2021-04-27 18:46:16 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'body': {'apiVersion': 'networking.istio.io/v1alpha3', 'kind': 'VirtualService', 'metadata': {'annotations': {'kubectl.kubernetes.io/last-applied-configuration': '{"apiVersion":"networking.istio.io/v1alpha3","kind":"VirtualService","metadata":{"annotations":{},"name":"mg-v1-vs","namespace":"default"},"spec":{"hosts":["mg-v1"],"http":[{"route":[{"destination":{"host":"mg-v1","port":{"number":8081},"subset":"primary"}}]}]}}\n'}, 'creationTimestamp': '2021-04-26T19:12:53Z', 'generation': 2, 'managedFields': [{'apiVersion': 'networking.istio.io/v1alpha3', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:annotations': {'.': {}, 'f:kubectl.kubernetes.io/last-applied-configuration': {}}}, 'f:spec': {'.': {}, 'f:hosts': {}, 'f:http': {}}}, 'manager': 'kubectl-client-side-apply', 'operation': 'Update', 'time': '2021-04-26T19:12:53Z'}], 'name': 'mg-v1-vs', 'namespace': 'default', 'resourceVersion': '3504', 'uid': '14949f29-652e-4db8-8951-371976c9fe8f'}, 'spec': {'hosts': ['mg-v1'], 'http': [{'route': [{'destination': {'host': 'mg-v1', 'port': {'number': 8081}, 'subset': 'primary'}}]}]}}, 'headers': {'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': 'ca338ed9-6f9e-4cbe-97a8-df98999be000', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'b23d468f-1284-456c-b90c-415700e009a5', 'Date': 'Tue, 27 Apr 2021 16:46:16 GMT', 'Content-Length': '1081'}}'
[36m[2021-04-27 18:46:16 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-27 18:46:16 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:46:17 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'rollback'
[36m[2021-04-27 18:46:17 DEBUG] [python:166][39m Control 'after_rollback_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-27 18:46:19 INFO] [run:421][39m Experiment ended with status: completed
[36m[2021-04-27 18:46:19 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'experiment'
[36m[2021-04-27 18:46:19 DEBUG] [python:166][39m Control 'after_experiment_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-27 18:46:22 DEBUG] [__init__:72][39m Cleaning up controls
[36m[2021-04-27 18:46:22 DEBUG] [__init__:188][39m Cleaning up global control 'chaosiq-cloud'
[36m[2021-04-27 18:46:22 DEBUG] [python:159][39m Control module '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py' does not declare 'cleanup_control'
[36m[2021-04-27 18:46:22 DEBUG] [caching:42][39m Clearing activities cache
[36m[2021-04-27 16:46:33 DEBUG][39m ###############################################################################
[36m[2021-04-27 16:46:33 DEBUG][39m Running command 'report'
[36m[2021-04-27 16:46:33 DEBUG][39m Using settings file '/.chaostoolkit/settings.yaml'
[33m[2021-04-27 16:46:33 WARNING][39m 
    There is a new version (1.9.0) of the chaostoolkit available.
    You may upgrade by typing:
    
    $ pip install -U chaostoolkit
    
    Please review changes at https://github.com/chaostoolkit/chaostoolkit/blob/master/CHANGELOG.md
    
[36m[2021-04-27 16:46:33 DEBUG][39m Building activity cache...
[36m[2021-04-27 16:46:33 DEBUG][39m Cached 2 activities
